In [1]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [3]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [4]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [5]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [6]:
x = np.ones(2, dtype=np.int64)

In [7]:
x

array([1, 1], dtype=int64)

In [8]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [9]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [10]:
arr.sort()

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])


In [17]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
a = np.arange(6)

In [19]:
a

array([0, 1, 2, 3, 4, 5])

In [22]:
b = a.reshape(2,3)

In [23]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
a = np.array([1, 2, 3, 4, 5, 6])

In [26]:
a.shape

(6,)

In [27]:
data = np.array([1, 2, 3])

In [28]:
data[0]

1

In [29]:
data[0:2]

array([1, 2])

In [30]:
data[1:]

array([2, 3])

In [31]:
data[-2:]

array([2, 3])