In [1]:
import numpy as np 
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a*b

array([2., 4., 6.])

In [2]:
a = np.array([1.0, 2.0, 3.0])
b=2
a*b

array([2., 4., 6.])

In [4]:
a =np.array([[ 0.0,  0.0,  0.0],
           [10.0, 10.0, 10.0],
           [20.0, 20.0, 20.0],
           [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])

In [5]:
a+b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [6]:
a = np.array([0.0, 10.0, 20.0, 30.0])

In [7]:
b = np.array([1.0, 2.0, 3.0])

In [12]:
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [14]:
b = np.array([1.0, 2.0, 3.0, 4.0])

In [15]:
a + b

array([ 1., 12., 23., 34.])

In [16]:
from numpy import array, argmin, sqrt, sum


In [18]:
observation = np.array([111.0, 188.0])

In [19]:
codes = array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])

In [20]:
diff = codes - observation

In [21]:
diff

array([[ -9.,  15.],
       [ 21.,   5.],
       [-66., -33.],
       [-54., -15.]])

In [22]:
dist = sqrt(sum(diff**2,axis=-1))

In [23]:
dist

array([17.49285568, 21.58703314, 73.79024326, 56.04462508])

In [24]:
argmin(dist)

0