In [1]:
import numpy as np 

In [2]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [3]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])


In [5]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [6]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [7]:
np.dot(x, y) #equivalent

array([[ 28.,  64.],
       [ 67., 181.]])

In [8]:
 np.ones(3)

array([1., 1., 1.])

In [9]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [10]:
from numpy.linalg import inv, qr


In [11]:
X = np.random.randn(5, 5)

In [12]:
X

array([[-1.30429248, -2.29257421,  0.39300443,  0.07511584,  0.55439607],
       [-0.09577308,  0.45616627,  0.95648296,  0.48633685,  1.26948293],
       [ 0.23883853,  0.72453384, -0.1911693 ,  0.45193636, -1.30292066],
       [ 1.9133871 , -0.43715595, -0.67414184,  0.3023698 , -1.76084388],
       [ 1.95105443,  0.63562824, -1.5569594 , -0.38489609, -0.77765738]])

In [13]:
mat = X.T.dot(X)


In [14]:
mat

array([[ 9.23505877e+00,  3.52324217e+00, -4.97746347e+00,
        -2.09013943e-01, -6.04229241e+00],
       [ 3.52324217e+00,  6.58406206e+00, -1.29812743e+00,
         2.51432201e-04, -1.36044656e+00],
       [-4.97746347e+00, -1.29812743e+00,  3.98444762e+00,
         8.03724864e-01,  4.07903684e+00],
       [-2.09013943e-01,  2.51432201e-04,  8.03724864e-01,
         6.85984894e-01, -1.62905676e-01],
       [-6.04229241e+00, -1.36044656e+00,  4.07903684e+00,
        -1.62905676e-01,  7.32186632e+00]])

In [15]:
inv(mat)

array([[ 7.77924455e-01, -1.73418467e-01,  1.51328772e+00,
        -1.59978983e+00, -2.68900116e-01],
       [-1.73418467e-01,  2.09164394e-01, -1.79041729e-01,
         1.56614105e-01, -1.01845222e-03],
       [ 1.51328772e+00, -1.79041729e-01,  4.94446137e+00,
        -5.72770393e+00, -1.66645563e+00],
       [-1.59978983e+00,  1.56614105e-01, -5.72770393e+00,
         8.17540259e+00,  2.08170995e+00],
       [-2.68900116e-01, -1.01845222e-03, -1.66645563e+00,
         2.08170995e+00,  8.89185532e-01]])

In [16]:
#The expression X.T.dot(X) computes the dot product of X with its transpose X.T.