In [5]:

# NumPy ndarray
import numpy as np
data= np.random.randn(2, 3)
print(data)

[[-0.51564435  0.32900893  1.32530788]
 [-0.89318051  0.96072632 -1.49925875]]


In [6]:
data*data

array([[0.2658891 , 0.10824688, 1.75644098],
       [0.79777142, 0.92299506, 2.24777678]])

In [7]:
data+data

array([[-1.0312887 ,  0.65801786,  2.65061576],
       [-1.78636102,  1.92145263, -2.99851749]])

In [8]:
data.shape

(2, 3)