In [5]:

# NumPy ndarray
import numpy as np
data= np.random.randn(2, 3)
print(data)

[[-0.51564435  0.32900893  1.32530788]
 [-0.89318051  0.96072632 -1.49925875]]


In [6]:
data*data

array([[0.2658891 , 0.10824688, 1.75644098],
       [0.79777142, 0.92299506, 2.24777678]])

In [7]:
data+data

array([[-1.0312887 ,  0.65801786,  2.65061576],
       [-1.78636102,  1.92145263, -2.99851749]])

In [8]:
data.shape

(2, 3)

In [9]:
data1 = [6, 7.5, 8, 0, 1]

In [10]:
data1

[6, 7.5, 8, 0, 1]

In [11]:
arr1 = np.array(data1)

In [12]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [14]:
arr2=np.array(data2)

In [15]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.arange(15) #creating an array 


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [21]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [22]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [23]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [26]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [27]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [28]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])