In [1]:
#Tamires Soares- Exercises 
import numpy as np 
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x[:5] #first five elements 

array([0, 1, 2, 3, 4])

In [5]:
x[5:] #last five elements, array slice 

array([5, 6, 7, 8, 9])

In [6]:
 x[4:7] 

array([4, 5, 6])

In [7]:
x[::-1] # all elements, reversed


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [8]:
x2 = np.random.randint(10, size=(3, 4))

In [9]:
x2

array([[0, 3, 0, 0],
       [9, 1, 7, 5],
       [2, 8, 8, 1]])

In [10]:
x2[0, 0]

0

In [11]:
 x2[:2, :3] #multidimensional slice 

array([[0, 3, 0],
       [9, 1, 7]])

In [12]:
x2[:3, ::2]

array([[0, 0],
       [9, 7],
       [2, 8]])

In [13]:
x2[0]

array([0, 3, 0, 0])

In [14]:
grid = np.arange(1, 10).reshape((3, 3))

In [15]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
grid=np.arange(1,10)

In [18]:
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
 x = np.array([1, 2, 3])

In [20]:
x

array([1, 2, 3])

In [21]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [23]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])


In [24]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [25]:
grid = np.arange(16).reshape((4, 4))

In [26]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
upper, lower = np.vsplit(grid, [2])

In [28]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
#doubt 
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [33]:
left, right = np.hsplit(grid, [2])

In [34]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [35]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [37]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [38]:
x = np.arange(9).reshape((3, 3))

In [39]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [41]:
x = np.arange(4)

In [42]:
x

array([0, 1, 2, 3])

In [43]:
print("x + 5 =", x + 5)

x + 5 = [5 6 7 8]


In [44]:
print("x * 2 =", x * 2)

x * 2 = [0 2 4 6]


In [45]:
#absolute values 
x = np.array([-2, -1, 0, 1, 2])
abs(x)


array([2, 1, 0, 1, 2])