In [2]:
import numpy as np
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

In [3]:
x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [4]:
x[1]

('Fido', 3, 27.)

In [6]:
x[0]

('Rex', 9, 81.)

In [7]:
x['age'] = 5

In [8]:
x

array([('Rex', 5, 81.), ('Fido', 5, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [9]:
d = np.dtype([('x', 'i8'), ('y', 'f4')])

In [10]:
d.names

('x', 'y')

In [11]:
d.fields

mappingproxy({'x': (dtype('int64'), 0), 'y': (dtype('float32'), 8)})

In [12]:
x = np.array([(1, 2, 3), (4, 5, 6)], dtype='i8, f4, f8')

In [13]:
x[1] = (7, 8, 9)

In [14]:
x

array([(1, 2., 3.), (7, 8., 9.)],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '<f8')])

In [15]:
x = np.zeros(2, dtype='i8, f4, ?, S1')

In [16]:
x

array([(0, 0., False, b''), (0, 0., False, b'')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [17]:
x[:] = 3

In [18]:
x

array([(3, 3.,  True, b'3'), (3, 3.,  True, b'3')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [19]:
x = np.array([(1, 2), (3, 4)], dtype=[('foo', 'i8'), ('bar', 'f4')])

In [20]:
x

array([(1, 2.), (3, 4.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

In [21]:
x['foo']

array([1, 3], dtype=int64)

In [22]:
x['foo']=10

In [23]:
x

array([(10, 2.), (10, 4.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

In [24]:
x = np.array([(1, 2), (3, 4)], dtype=[('foo', 'i8'), ('bar', 'f4')])

In [26]:
x['bar'] = 100

In [27]:
x

array([(1, 100.), (3, 100.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

In [28]:
a = np.array([2, 3, 4], dtype=np.uint32)

In [29]:
b = np.array([5, 6, 7], dtype=np.uint32)

In [30]:
a-b

array([4294967293, 4294967293, 4294967293], dtype=uint32)

In [31]:
c_signed32 = a - b.astype(np.int32)

In [32]:
c_signed32

array([-3, -3, -3], dtype=int64)